repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: debug-statements
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
  - id: check-merge-conflict
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-json
  - id: forbid-new-submodules
  - id: no-commit-to-branch
  - id: flake8
    args: ['--exclude=docs/*,*migrations*', '--ignore=E501, E203']

- repo: local
  hooks:
  - id: pipenv-check
    name: Pipenv Check
    entry: pipenv check
    language: system
    files: Pipfile
    verbose: false
    pass_filenames: false

  - id: check-datetime-now
    name: check_datetime_now
    description: Prefer datetime.utcnow()
    language: pygrep
    entry: 'datetime\.now\(\)'
    types: [python]

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.20
  hooks:
  - id: isort
    args: ['--check-only', '--diff']

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.4.0
  hooks:
    - id: python-check-mock-methods

- repo: https://github.com/python/black
  rev: stable
  hooks:
    - id: black
